---
title: "connor_shiny"
author: "Connor Flynn"
date: "5/30/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(shiny)
```

```{r}
data <- read_csv(here("cleaned_data/master_data_pivot.csv"))
```


```{r}
ui <- fluidPage(
  titlePanel("Line Graph of Selected Data"),
  sidebarLayout(
    sidebarPanel(
      selectInput("site", "Select Site:", choices = unique(data$site)),
      selectInput("site_specific", "Select Site Specific:", choices = NULL),
      selectInput("variable", "Select Variable:", choices = unique(data$variable))
    ),
    mainPanel(
      plotOutput("linePlot")
    )
  )
)

```


```{r}
server <- function(input, output, session) {
  
  # Update site_specific choices based on selected site
  observe({
    selected_site <- input$site
    updateSelectInput(session, "site_specific", choices = unique(data[data$site == selected_site, "site_specific"]))
  })
  
  # Render the line plot
  output$linePlot <- renderPlot({
    filtered_data <- data %>%
      filter(site == input$site,
             site_specific == input$site_specific,
             variable == input$variable)
    
    ggplot(filtered_data, aes(x = date_time_hst, y = value)) +
      geom_line() +
      labs(title = paste("Line Graph of", input$variable, "at", input$site, "-", input$site_specific),
           x = "Date Time",
           y = input$variable)
  })
}

```


```{r}
shinyApp(ui = ui, server = server)

```

