---
title: "Maunalua Fishpond Heritage Center Data Dashboard (Beta)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    social: menu
    source_code: embed
    theme: yeti
runtime: shiny
---

```{r global, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(here)
library(plotly)
library(shiny)
library(rsconnect)

options(scipen = 99)
```

```{r, include=FALSE}
all_data <- read_csv(here("cleaned_data/all_data_distinct_seq_wider.csv"))
```

```{r include=FALSE}
all_data_longer <- all_data %>% 
  pivot_longer(cols = dissolved_oxygen_mg_l:temp_celsius, names_to = "variable", values_to = "value")
```

```{r echo=FALSE}
data_kalauhaihai <- all_data_longer %>% 
  filter(site == "Kalauhaihai")

data_kanewai <- all_data_longer %>% 
  filter(site == "Kanewai")
```

```{r echo=FALSE}
unique_site <- unique(all_data_longer$site)
unique_variable <- unique(all_data_longer$variable)
```

Kalauhaiahi
=========================================================
```{r echo=FALSE}
selectInput("Select_Variable", label = "Select Input", choices = unique_variable)
```

```{r echo=FALSE}
filtered_data_kalauhaihai <- reactive({
  data_kalauhaihai %>% filter(variable == input$Select_Variable)
})
```

```{r eval=FALSE, include=FALSE}
output$plot <- renderPlotly({
  all_data_longer %>%
    select(-site_specific) %>%
    filter(site == "Kalauhaihai") %>%
    group_by(variable) %>%
    mutate(value = scale(value)) %>%
    ungroup() %>%
    filter(str_detect(variable, if_else(input$Select_Variable == "All", "", input$Select_Variable))) %>%
    ggplot(aes(date_time, value)) +
    geom_line() +
    labs(x = "Date Time", y = input$Select_Variable, title = input$Select_Variable) +
    theme_minimal()
})


plotlyOutput("plot")
```

```{r eval=FALSE, include=FALSE}
output$plot <- renderPlotly({
  filtered_data <- all_data_longer %>%
    filter(site == "Kalauhaihai") %>%
    filter(variable == input$Select_Variable) %>%
    ggplot(aes(date_time, value)) +
    geom_line(color = "steelblue") +
    labs(x = "Date Time", y = input$Select_Variable, title = input$Select_Variable) +
    theme_minimal()

  ggplotly(filtered_data)
})

plotlyOutput("plot")

```

```{r echo=FALSE}
output$plot <- renderPlotly({
  ggplotly(
    ggplot(filtered_data_kalauhaihai(), aes(date_time, value)) +
      geom_point(color = "steelblue") +
      labs(x = "Date Time", y = paste(input$Select_Variable), title = paste(input$Select_Variable)
 ) +
      theme_minimal() 
  )
})

plotlyOutput("plot")
```

Row
----------------------------------------------------------------------------
```{r echo=FALSE}
output$faceted_plots <- renderPlotly({
  ggplotly(
    ggplot(data_kalauhaihai, aes(date_time, value, color = variable)) +
      geom_point() +
      facet_wrap(~variable, scales = "free") +
      labs(x = "Date Time", y = "Variable", title = "Kalauhaihai") +
      theme_minimal() 
  )
})

plotlyOutput("faceted_plots")
```

Row
---------------------------------------------------------
```{r echo=FALSE}
selectInput("Select_Site", label = "Select Site", choices = unique_site)
```


Kanewai
=========================================================
```{r echo=FALSE}
 selectInput("Select Variable", label = "Select Input", choices = unique_variable)
```

```{r echo=FALSE}
filtered_data_kanewai <- reactive({
  data_kanewai %>% filter(variable == input$Select_Variable)
})
```

```{r echo=FALSE}
output$plot2 <- renderPlotly({
  ggplotly(
    ggplot(filtered_data_kanewai(), aes(date_time, value)) +
      geom_line(color = "steelblue") +
      labs(x = "Date Time", y = paste(input$Select_Variable), title = paste(input$Select_Variable)
 ) +
      theme_minimal() 
  )
})

plotlyOutput("plot2")
```

Row
----------------------------------------------------------------------------
```{r echo=FALSE}
output$faceted_plots2 <- renderPlotly({
  ggplotly(
    ggplot(data_kanewai, aes(date_time, value, color = variable)) +
      geom_line() +
      facet_wrap(~variable, scales = "free") +
      labs(x = "Date Time", y = "Variable", title = "Kalauhaihai") +
      theme_minimal()
  )
})

plotlyOutput("faceted_plots2")
```




