---
title: "Can we For Loop!?"
author: "Connor Flynn"
date: "4/25/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```



```{r eval=FALSE, include=FALSE}
# Set the working directory to the project root folder
here::set_here()

# Define the path to the raw data folder
raw_data_folder <- here("raw_data", "raw_pH")

# Get the list of files in the raw_pH folder
file_list <- list.files(path = raw_data_folder, full.names = TRUE)

# Define a function to read and clean the column names
read_and_clean_data <- function(file_path) {
  # Check if file is .csv or .txt
  file_ext <- tools::file_ext(file_path)
  
  # Read the file based on the extension
  if (file_ext == "csv") {
    data <- read_csv(file_path)
  } else if (file_ext == "txt") {
    data <- read_tsv(file_path)
  } else {
    stop("Unsupported file format")
  }

  if (file_ext == "csv") {
  data <- read_csv(file_path)
} else if (file_ext == "txt") {
  # Read the first line to check if it starts with "Serial"
  first_line <- readLines(file_path, n = 1)

  if (startsWith(first_line, "Serial")) {
    data <- read_tsv(file_path, skip = 1)
  } else {
    data <- read_tsv(file_path)
  }
} else {
  stop("Unsupported file format")
}



  # Clean column names using janitor's clean_names()
  data <- data %>% clean_names()

  return(data)
}

# Initialize empty data frames for each file
# df1 <- df2 <- df3 <- df4 <- data.frame()
# 
# # Loop through each file, read, and clean the data
# for (i in seq_along(file_list)) {
#   data <- read_and_clean_data(file_list[i])
# 
#   # Merge date and time columns into a single datetime column
#   if ("date" %in% colnames(data) && "time" %in% colnames(data)) {
#     data <- data %>%
#       mutate(datetime = as.POSIXct(paste(date, time), format = "%Y-%m-%d %H:%M:%S"))
#   }
# 
# 
# 
# 
#   # Assign each dataframe to a variable based on file index
#   assign(paste0("df", i), data)
# }
# 
#   
#   # Assign data to respective data frames (df1, df2, df3, df4)
#   assign(paste0("df", i), data)
# }

df1 <- df2 <- df3 <- df4 <- data.frame()

# Loop through each file, read, and clean the data
for (i in seq_along(file_list)) {
  data <- read_and_clean_data(file_list[i])

  #Merge date and time columns into a single datetime column
  if ("date" %in% colnames(data) && "time" %in% colnames(data)) {
    data <- data %>%
      unite(date_time_hst, date, time, sep = " ") %>%
      mutate(date_time_hst = as.POSIXctformat(data$date_time_hst = "%d-%m-%Y %H:%M:%S"))
  }

  if ("date_time_hst" %in% colnames(data) && is.character(data$date_time_hst)) {
  data$date_time_hst <- as.POSIXct(data$date_time_hst, format = "%m/%d/%Y %H:%M:%S")
}

  


  

  # Assign each dataframe to a variable based on file index
  assign(paste0("df", i), data)
}

# Assign data to respective data frames (df1, df2, df3, df4)
assign(paste0("df", i), data)


# Now you have df1, df2, df3, and df4 dataframes with merged datetime column


```







```{r}
# Set the working directory to the project root folder
here::set_here()

# Define the path to the raw data folder
raw_data_folder <- here("raw_data", "raw_pH")

# Get the list of files in the raw_pH folder
file_list <- list.files(path = raw_data_folder, full.names = TRUE)

# Define a function to read and clean the column names
read_and_clean_data <- function(file_path) {
  # Check if file is .csv or .txt
  file_ext <- tools::file_ext(file_path)
  
  # Read the file based on the extension
  if (file_ext == "csv") {
    data <- read_csv(file_path)
  } else if (file_ext == "txt") {
    data <- read_tsv(file_path)
  } else {
    stop("Unsupported file format")
  }

  if (file_ext == "csv") {
  data <- read_csv(file_path)
} else if (file_ext == "txt") {
  # Read the first line to check if it starts with "Serial"
  first_line <- readLines(file_path, n = 1)

  if (startsWith(first_line, "Serial")) {
    data <- read_tsv(file_path, skip = 1)
  } else {
    data <- read_tsv(file_path)
  }
} else {
  stop("Unsupported file format")
}



  # Clean column names using janitor's clean_names()
  data <- data %>% clean_names()

  return(data)
}

#Initialize empty data frames for each file
df1 <- df2 <- df3 <- df4 <- data.frame()

# Loop through each file, read, and clean the data
for (i in seq_along(file_list)) {
  data <- read_and_clean_data(file_list[i])
  
  # Change columns containing "date" in their names to "date_time_hst"
  date_columns <- grep("date", colnames(data), ignore.case = TRUE)
  if (length(date_columns) > 0) {
    colnames(data)[date_columns] <- "date_time_hst"
  }
  
  # Change columns containing "p_h" in their names to "ph_level"
  ph_columns <- grep("p_h", colnames(data), ignore.case = TRUE)
  if (length(ph_columns) > 0) {
    colnames(data)[ph_columns] <- "pH"
  }

  # Merge date and time columns into a single datetime column
  if ("date_time_hst" %in% colnames(data) && "time" %in% colnames(data)) {
    data <- data %>%
      mutate(date_time_hst = as.POSIXct(paste(date_time_hst, time), format = "%d-%m-%y %H:%M:%S"))
  }
  
  
  # Set the class of "date_time_hst" column to POSIXct with the specified format
  if ("date_time_hst" %in% colnames(data)) {
    date_format <- c("%m/%d/%Y %H:%M:%S", "%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M:%S %Z")
    for (format in date_format) {
      data$date_time_hst <- as.POSIXct(data$date_time_hst, format = format, tz = "UTC", tryFormats = c(format))
    }
  }
  
  # Assign each dataframe to a variable based on file index
  assign(paste0("df", i), data)
}

# Assign data to respective data frames (df1, df2, df3, df4)
assign(paste0("df", i), data)

# Combine all dataframes into one dataframe and select only the required columns
pH_joined <- bind_rows(df1, df2, df3, df4) %>%
  select(date_time_hst, pH)

```



