---
title: "joining_for_loops"
author: "Anson Ekau"
date: "2024-05-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) #A toolbox full of more toolboxes
library(here)#Sets working directory, type the following in console or in a code chunk. 'here::set_here()' 
library(naniar)
```

#Read in files
```{r}
oxygen <- read_csv(here("cleaned_data/oxygen_joined.csv"))
pH <- read_csv(here("cleaned_data/pH_joined.csv"))
temp <- read_csv(here("cleaned_data/temp_joined.csv"))
```
#Join files
```{r}
all_data <- bind_rows(oxygen,
          pH,
          temp)
```

```{r}
write_csv(all_data, here("cleaned_data/master_data.csv"))
```

```{r}
all_data_pivot <- all_data %>% 
  pivot_longer(cols = c(oxygen, temperature, pH), 
               names_to = "variable", 
               values_to = "value") %>%
  filter(!is.na(value))
```


```{r}
all_data_pivot_dupe <- all_data_pivot %>%
  distinct(date_time_hst, site, site_specific, variable, .keep_all = TRUE)
```

```{r}
all_data_pivot %>%
  group_by(site, site_specific, variable) %>%
  summarise(percent_missing = mean(is.na(value)) * 100)
```

```{r}
#write a for loop checking for n/a in site_specific column and replacing them with the character "test". the data set is called all_data_pivot

# Assuming all_data_pivot is your data frame
for (i in 1:nrow(all_data_pivot_dupe)) {
  if (is.na(all_data_pivot_dupe[i, "site_specific"])) {
    all_data_pivot_dupe[i, "site_specific"] <- "General"
  }
}


```

```{r}
write_csv(all_data_pivot_dupe, here("cleaned_data/master_data_pivot.csv"))
```

