---
title: "Untitled"
author: "Anson Ekau"
date: "2024-03-07"
output: html_document
---

```{r setup, include=FALSE}
library(shiny)
library(tidyverse)
library(here)
library(plotly)
library(shiny)
library(rsconnect)
library(bslib) #custom theme

options(scipen = 99)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
all_data <- read_csv(here("cleaned_data/master_dataframe.csv"))
```

```{r}
unique_site <- unique(all_data$site)
unique_site_specific <- unique(all_data$site_specific)
unique_variable <- unique(all_data$variable)
```

```{r echo=FALSE}
selectInput("Select_Variable", label = "Select Variable", choices = unique_variable, selected = "pH")
selectInput("Select_Site", label = "Select Site", choices = unique_site, selected = "Kanewai")
selectInput("Select_Site_Specific", label = "Select Specific Site", choices = unique_site_specific)
```

```{r echo=FALSE}
filtered_data <- reactive({
  all_data %>% 
    filter(variable == input$Select_Variable,
           site == input$Select_Site,
           site_specific == input$Select_Site_Specific)
})
```

```{r}
ui <- fluidPage(
  titlePanel("Maunalua Fishpond Heritage Center Dashboard"),
  sidebarLayout(
    sidebarPanel(),
    mainPanel(
      h1("Place filter here"),
    )
  )
)

server <- function(input, output) {
  output$plot <- renderPlotly({
  a <- ggplot(filtered_data(), aes(date_time, value)) +
      geom_line(color = "mediumaquamarine") +
      labs(x = "Date Time", y = paste(input$Select_Variable), title = paste(input$Select_Variable)
 ) +
      theme_minimal() 
 if(input$Select_Variable == "dissolved_oxygen_mg_l") {
  a <- a + geom_hline(yintercept = 2, linetype = "dashed", color = "red", size = 0.5) +
    annotate(geom="text",x = as.POSIXct("2023-02-18 21:10:00"), y = 2.5, label = "hypoxic", colour = "red")
 }
  ggplotly(a)
})

plotlyOutput("plot")

  
}

shinyApp(ui = ui, server = server)


```

```{r}
output$plot <- renderPlotly({
  a <- ggplot(filtered_data(), aes(date_time, value)) +
      geom_line(color = "mediumaquamarine") +
      labs(x = "Date Time", y = paste(input$Select_Variable), title = paste(input$Select_Variable)
 ) +
      theme_minimal() 
 if(input$Select_Variable == "dissolved_oxygen_mg_l") {
  a <- a + geom_hline(yintercept = 2, linetype = "dashed", color = "red", size = 0.5) +
    annotate(geom="text",x = as.POSIXct("2023-02-18 21:10:00"), y = 2.5, label = "hypoxic", colour = "red")
 }
  ggplotly(a)
})

plotlyOutput("plot")

```



