---
title: "Maunalua Fishpond Heritage Center Data Dashboard (Beta)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    social: menu
    source_code: embed
    theme: yeti
runtime: shiny
---

```{r global, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(here)
library(plotly)
library(shiny)
library(rsconnect)

options(scipen = 99)
```

Home
=========================================================


```{r echo=FALSE}
all_data <- read_csv(here("cleaned_data/master_dataframe_distinct.csv"))
```

```{r echo=FALSE}
unique_site <- unique(all_data$site)
unique_site_specific <- unique(all_data$site_specific)
unique_variable <- unique(all_data$variable)
```


```{r echo=FALSE}
selectInput("Select_Variable", label = "Select Variable", choices = unique_variable)
selectInput("Select_Site", label = "Select Site", choices = unique_site)
selectInput("Select_Site_Specific", label = "Select Specific Site", choices = unique_site_specific)
```


```{r echo=FALSE}
filtered_data <- reactive({
  all_data %>% 
    filter(variable == input$Select_Variable,
           site == input$Select_Site,
           site_specific == input$Select_Site_Specific)
})
```


Row
---------------------------------------------------------


```{r echo=FALSE}
output$plot <- renderPlotly({
  ggplotly(
    ggplot(filtered_data(), aes(date_time, value)) +
      geom_line(color = "steelblue") +
      labs(x = "Date Time", y = paste(input$Select_Variable), title = paste(input$Select_Variable)
 ) +
      theme_minimal() 
  )
})

plotlyOutput("plot")

```



Kanewai Temperature
=========================================================


```{r echo=FALSE}
kanewai_temp <- all_data %>% 
  filter(site == "Kanewai" & variable == "temp_celsius")
```




```{r echo=FALSE}
output$plot2 <- renderPlotly({
  ggplotly(
    ggplot(kanewai_temp, aes(date_time, value, color = site_specific)) +
      geom_line() +
      facet_wrap(~site_specific) +
      theme_minimal() +
      labs(x = "Date Time", y = "Temperature (°C)")
  )
})

plotlyOutput("plot2")
```



Kalauhaihai Temperature
=========================================================


```{r echo=FALSE}
kalauhaihai_temp <- all_data %>% 
  filter(site == "Kalauhaihai" & variable == "temp_celsius")
```




```{r echo=FALSE}
output$plot3 <- renderPlotly({
  ggplotly(
    ggplot(kalauhaihai_temp, aes(date_time, value, color = site_specific)) +
      geom_line() +
      facet_wrap(~site_specific, scales = "free_x") +
      theme_minimal() +
      labs(x = "Date Time", y = "Temperature (°C)")
  )
})

plotlyOutput("plot3")
```


Variable Interactions
=========================================================


```{r echo=FALSE}
unique_site <- unique(all_data$site)
unique_variable1 <- unique(all_data$variable)
unique_variable2 <- unique(all_data$variable)
```


```{r echo=FALSE}
selectInput("Select_Variable1", label = "Select Variable 1", choices = unique_variable1)
selectInput("Select_Variable2", label = "Select Variable 2", choices = unique_variable2)
#selectInput("Select_Site", label = "Select Site", choices = unique_site)

```


```{r echo=FALSE}
filtered_interactive_data <- reactive({
  all_data %>% 
    filter(variable == input$Select_Variable1 | variable == input$Select_Variable2,)
})
```





```{r echo=FALSE}
output$plot4 <- renderPlotly({
  ggplotly(
    ggplot(filtered_interactive_data(), aes(input$Select_Variable1, input$Select_Variable2)) +
      geom_point(color = "steelblue") +
      geom_smooth() +
      theme_minimal() 
  )
})

plotlyOutput("plot4")
```



