---
title: "Temp Cleaning"
author: "Anson Ekau"
date: "2023-07-15"
output: html_document
---

#Load in packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```


# Read in Temp data — 28 sets
```{r Sept2021Feb2022 KalauhaihaiAuwaiUnderBridge, message=FALSE, warning=FALSE}
data_temp_Sept2021Feb2022_KalauhaihaiAuwaiUnderBridge <- read_csv(here("raw_data/raw_temperature/data_temp_Sept2021Feb2022_KalauhaihaiAuwaiUnderBridge_20970094.csv"), skip = 1)
```

```{r Sept2021June2022 KalauhaihaiMakaha, message=FALSE, warning=FALSE}
data_temp_Sept2021June2022_KalauhaihaiMakaha <- read_csv(here("raw_data/raw_temperature/data_temp_Sept2021June2022_KalauhaihaiMakaha_20970115.csv"), skip = 1)
```

```{r MarApr2022 KalauhaihaiAuwai, message=FALSE, warning=FALSE}
data_temp_MarApr2022_KalauhaihaiAuwai <- read_csv(here("raw_data/raw_temperature/data_temp_MarApr2022_KalauhaihaiAuwai_20970122.csv"), skip = 1)
```

```{r MarApr2022 KalauhaihaiCoconutTree, message=FALSE, warning=FALSE}
data_temp_MarApr2022_KalauhaihaiCoconutTree <- read_csv(here("raw_data/raw_temperature/data_temp_MarApr2022_KalauhaihaiCoconutTree_20970110.csv"), skip = 1)
```

```{r MarApr2022 KalauhaihaiGarage, message=FALSE, warning=FALSE}
data_temp_MarApr2022_KalauhaihaiGarage <- read_csv(here("raw_data/raw_temperature/data_temp_MarApr2022_KalauhaihaiGarage_20970094.csv"), skip = 1)
```

```{r MarApr2022 KalauhaihaiHighway, message=FALSE, warning=FALSE}
data_temp_MarApr2022_KalauhaihaiHighway <- read_csv(here("raw_data/raw_temperature/data_temp_MarApr2022_KalauhaihaiHighway_20970092.csv"), skip = 1)
```

```{r MarApr2022 KalauhaihaiMakaha, message=FALSE, warning=FALSE}
data_temp_MarApr2022_KalauhaihaiMakaha <- read_csv(here("raw_data/raw_temperature/data_temp_MarApr2022_KalauhaihaiMakaha_20970102.csv"), skip = 1)
```

```{r MarApr2022 KalauhaihaiOctopusTree, message=FALSE, warning=FALSE}
data_temp_MarApr2022_KalauhaihaiOctopusTree <- read_csv(here("raw_data/raw_temperature/data_temp_MarApr2022_KalauhaihaiOctopusTree_20970118.csv"), skip = 1)
```

```{r JuneOct2022 KalauhaihaiGarage, message=FALSE, warning=FALSE}
data_temp_JuneOct2022_KalauhaihaiGarage <- read_tsv(here("raw_data/raw_temperature/data_temp_JuneOct2022_KalauhaihaiGarage_20970092.txt"))
```

```{r JuneOct2022 KalauhaihaiMakaha, message=FALSE, warning=FALSE}
data_temp_JuneOct2022_KalauhaihaiMakaha <- read_tsv(here("raw_data/raw_temperature/data_temp_JuneOct2022_KalauhaihaiMakaha_20970109.txt"))
```

```{r JuneOct2022 KanewaiAuwaiMakaiSideFootBridge, message=FALSE, warning=FALSE}
data_temp_JuneOct2022_KanewaiAuwaiMakaiSideFootBridge <- read_tsv(here("raw_data/raw_temperature/data_temp_JuneOct2022_KanewaiAuwaiMakaiSideFootBridge_20970107.txt"))
```

```{r JuneOct2022 KanewaiFishpondLedgeEdgeNorfolk, message=FALSE, warning=FALSE}
data_temp_JuneOct2022_KanewaiFishpondLedgeEdgeNorfolk <- read_tsv(here("raw_data/raw_temperature/data_temp_JuneOct2022_KanewaiFishpondLedgeEdgeNorfolk_20970122.txt"))
```

```{r JuneOct2022 KanewaiFishpondShadeUnderXmasBerry, message=FALSE, warning=FALSE}
data_temp_JuneOct2022_KanewaiFishpondShadeUnderXmasBerry <- read_tsv(here("raw_data/raw_temperature/data_temp_JuneOct2022_KanewaiFishpondShadeUnderXmasBerry_20970123.txt"))
```

```{r JuneOct2022_KanewaiSpringLedge, message=FALSE, warning=FALSE}
data_temp_JuneOct2022_KanewaiSpringLedge <- read_tsv(here("raw_data/raw_temperature/data_temp_JuneOct2022_KanewaiSpringLedge_20970093.txt"))
```

```{r OctNov2022 KalauhaihaiGarage, message=FALSE, warning=FALSE}
data_temp_OctNov2022_KalauhaihaiGarage <- read_tsv(here("raw_data/raw_temperature/data_temp_OctNov2022_KalauhaihaiGarage_21445019.txt"))
```

```{r OctNov2022 KalauhaihaiMakaha, message=FALSE, warning=FALSE}
data_temp_OctNov2022_KalauhaihaiMakaha <- read_tsv(here("raw_data/raw_temperature/data_temp_OctNov2022_KalauhaihaiMakaha_21445021.txt"))
```

```{r Oct2022Feb2023 KanewaiAuwaiMakaiSideFootBridge, message=FALSE, warning=FALSE}
data_temp_Oct2022Feb2023_KanewaiAuwaiMakaiSideFootBridge <- read_csv(here("raw_data/raw_temperature/data_temp_Oct2022Feb2023_KanewaiAuwaiMakaiSideFootBridge_20970110.csv"),skip = 1)
```

```{r Oct2022Feb2023 KanewaiFishpondLedgeEdgeNorfolk, message=FALSE, warning=FALSE}
data_temp_Oct2022Feb2023_KanewaiFishpondLedgeEdgeNorfolk <- read_csv(here("raw_data/raw_temperature/data_temp_Oct2022Feb2023_KanewaiFishpondLedgeEdgeNorfolk_20970094.csv"),skip = 1)
```

```{r Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry, message=FALSE, warning=FALSE}
data_temp_Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry <- read_csv(here("raw_data/raw_temperature/data_temp_Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry_20970115.csv"),skip = 1)
```

```{r Oct2022Feb2023 KanewaiSpringLedge, message=FALSE, warning=FALSE}
data_temp_Oct2022Feb2023_KanewaiSpringLedge <- read_csv(here("raw_data/raw_temperature/data_temp_Oct2022Feb2023_KanewaiSpringLedge_20970102.csv"),skip = 1)
```

```{r Nov2022Feb2023 KalauhaihaiGarage, message=FALSE, warning=FALSE}
data_temp_Nov2022Feb2023_KalauhaihaiGarage <- read_csv(here("raw_data/raw_temperature/data_temp_Nov2022Feb2023_KalauhaihaiGarage_20970109.csv"),skip = 1)
```

```{r Nov2022Feb2023 KalauhaihaiMakaha, message=FALSE, warning=FALSE}
data_temp_Nov2022Feb2023_KalauhaihaiMakaha <- read_csv(here("raw_data/raw_temperature/data_temp_Nov2022Feb2023_KalauhaihaiMakaha_20970123.csv"),skip = 1)
```

```{r FebApr2023 KalauhaihaiGarage, message=FALSE, warning=FALSE}
data_temp_FebApr2023_KalauhaihaiGarage <- read_csv(here("raw_data/raw_temperature/data_temp_FebApr2023_KalauhaihaiGarage_20970122.csv"),skip = 1)
```

```{r FebApr2023 KalauhaihaiMakaha, message=FALSE, warning=FALSE}
data_temp_FebApr2023_KalauhaihaiMakaha <- read_csv(here("raw_data/raw_temperature/data_temp_FebApr2023_KalauhaihaiMakaha_20970107.csv"),skip = 1)
```

```{r FebApr2023 KanewaiAuwaiMakaiSideFootBridge, message=FALSE, warning=FALSE}
data_temp_FebApr2023_KanewaiAuwaiMakaiSideFootBridge <- read_csv(here("raw_data/raw_temperature/data_temp_FebApr2023_KanewaiAuwaiMakaiSideFootBridge_20970093.csv"),skip = 1)
```

```{r FebApr2023 KanewaiFishpondLedgeEdgeNorfolk, message=FALSE, warning=FALSE}
data_temp_FebApr2023_KanewaiFishpondLedgeEdgeNorfolk <- read_csv(here("raw_data/raw_temperature/data_temp_FebApr2023_KanewaiFishpondLedgeEdgeNorfolk_20970108.csv"),skip = 1)
```

```{r FebApr2023_KanewaiFishpondShadeUnderXmasBerry, message=FALSE, warning=FALSE}
data_temp_FebApr2023_KanewaiFishpondShadeUnderXmasBerry <- read_csv(here("raw_data/raw_temperature/data_temp_FebApr2023_KanewaiFishpondShadeUnderXmasBerry_21445019.csv"),skip = 1)
```

```{r FebApr2023 KanewaiSpringLedge, message=FALSE, warning=FALSE}
data_temp_FebApr2023_KanewaiSpringLedge <- read_csv(here("raw_data/raw_temperature/data_temp_FebApr2023_KanewaiSpringLedge_20970092.csv"),skip = 1)
```

# Clean names 
```{r}
data_temp_Sept2021Feb2022_KalauhaihaiAuwaiUnderBridge <- data_temp_Sept2021Feb2022_KalauhaihaiAuwaiUnderBridge %>% 
  clean_names()

data_temp_Sept2021June2022_KalauhaihaiMakaha <- data_temp_Sept2021June2022_KalauhaihaiMakaha %>% 
  clean_names()

data_temp_MarApr2022_KalauhaihaiAuwai <- data_temp_MarApr2022_KalauhaihaiAuwai %>% 
  clean_names()

data_temp_MarApr2022_KalauhaihaiCoconutTree <- data_temp_MarApr2022_KalauhaihaiCoconutTree %>% 
  clean_names()

data_temp_MarApr2022_KalauhaihaiGarage <- data_temp_MarApr2022_KalauhaihaiGarage %>% 
  clean_names()

data_temp_MarApr2022_KalauhaihaiHighway <- data_temp_MarApr2022_KalauhaihaiHighway %>% 
  clean_names()

data_temp_MarApr2022_KalauhaihaiMakaha <- data_temp_MarApr2022_KalauhaihaiMakaha %>% 
  clean_names()

data_temp_MarApr2022_KalauhaihaiOctopusTree <- data_temp_MarApr2022_KalauhaihaiOctopusTree %>% 
  clean_names()

data_temp_JuneOct2022_KalauhaihaiGarage <- data_temp_JuneOct2022_KalauhaihaiGarage %>% 
  clean_names()

data_temp_JuneOct2022_KalauhaihaiMakaha <- data_temp_JuneOct2022_KalauhaihaiMakaha %>% 
  clean_names()

data_temp_JuneOct2022_KanewaiAuwaiMakaiSideFootBridge <- data_temp_JuneOct2022_KanewaiAuwaiMakaiSideFootBridge %>% 
  clean_names()

data_temp_JuneOct2022_KanewaiFishpondShadeUnderXmasBerry <- data_temp_JuneOct2022_KanewaiFishpondShadeUnderXmasBerry %>% 
  clean_names()

data_temp_JuneOct2022_KanewaiFishpondLedgeEdgeNorfolk <- data_temp_JuneOct2022_KanewaiFishpondLedgeEdgeNorfolk %>% 
  clean_names()

data_temp_JuneOct2022_KanewaiSpringLedge <- data_temp_JuneOct2022_KanewaiSpringLedge %>% 
  clean_names()

data_temp_OctNov2022_KalauhaihaiGarage <- data_temp_OctNov2022_KalauhaihaiGarage %>% 
  clean_names()

data_temp_OctNov2022_KalauhaihaiMakaha <- data_temp_OctNov2022_KalauhaihaiMakaha %>% 
  clean_names()

data_temp_Oct2022Feb2023_KanewaiAuwaiMakaiSideFootBridge <- data_temp_Oct2022Feb2023_KanewaiAuwaiMakaiSideFootBridge %>% 
  clean_names()

data_temp_Oct2022Feb2023_KanewaiFishpondLedgeEdgeNorfolk <- data_temp_Oct2022Feb2023_KanewaiFishpondLedgeEdgeNorfolk %>% 
  clean_names()

data_temp_Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry <- data_temp_Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry %>% 
  clean_names()

data_temp_Oct2022Feb2023_KanewaiSpringLedge <- data_temp_Oct2022Feb2023_KanewaiSpringLedge %>% 
  clean_names()

data_temp_Nov2022Feb2023_KalauhaihaiGarage <- data_temp_Nov2022Feb2023_KalauhaihaiGarage %>% 
  clean_names()

data_temp_Nov2022Feb2023_KalauhaihaiMakaha <- data_temp_Nov2022Feb2023_KalauhaihaiMakaha %>% 
  clean_names()

data_temp_FebApr2023_KalauhaihaiGarage <- data_temp_FebApr2023_KalauhaihaiGarage %>% 
  clean_names()

data_temp_FebApr2023_KalauhaihaiMakaha <- data_temp_FebApr2023_KalauhaihaiMakaha %>% 
  clean_names()

data_temp_FebApr2023_KanewaiAuwaiMakaiSideFootBridge <- data_temp_FebApr2023_KanewaiAuwaiMakaiSideFootBridge %>% 
  clean_names()

data_temp_FebApr2023_KanewaiFishpondLedgeEdgeNorfolk <- data_temp_FebApr2023_KanewaiFishpondLedgeEdgeNorfolk %>% 
  clean_names()

data_temp_FebApr2023_KanewaiFishpondShadeUnderXmasBerry <- data_temp_FebApr2023_KanewaiFishpondShadeUnderXmasBerry %>% 
  clean_names()

data_temp_FebApr2023_KanewaiSpringLedge <- data_temp_FebApr2023_KanewaiSpringLedge %>% 
  clean_names()
```

#Merge Date and Time columns for txt files
```{r message=FALSE, warning=FALSE}
data_temp_JuneOct2022_KalauhaihaiGarage <- data_temp_JuneOct2022_KalauhaihaiGarage %>%
  unite(date_time, date, time, sep = " ")

data_temp_JuneOct2022_KalauhaihaiGarage$date_time <- mdy_hms(data_temp_JuneOct2022_KalauhaihaiGarage$date_time)


data_temp_JuneOct2022_KalauhaihaiMakaha <- data_temp_JuneOct2022_KalauhaihaiMakaha %>%
  unite(date_time, date, time, sep = " ")

data_temp_JuneOct2022_KalauhaihaiMakaha$date_time <- mdy_hms(data_temp_JuneOct2022_KalauhaihaiMakaha$date_time)


data_temp_JuneOct2022_KanewaiAuwaiMakaiSideFootBridge <- data_temp_JuneOct2022_KanewaiAuwaiMakaiSideFootBridge %>%
  unite(date_time, date, time, sep = " ")

data_temp_JuneOct2022_KanewaiAuwaiMakaiSideFootBridge$date_time <- mdy_hms(data_temp_JuneOct2022_KanewaiAuwaiMakaiSideFootBridge$date_time)


data_temp_JuneOct2022_KanewaiFishpondLedgeEdgeNorfolk <- data_temp_JuneOct2022_KanewaiFishpondLedgeEdgeNorfolk %>%
  unite(date_time, date, time, sep = " ")

data_temp_JuneOct2022_KanewaiFishpondLedgeEdgeNorfolk$date_time <- mdy_hms(data_temp_JuneOct2022_KanewaiFishpondLedgeEdgeNorfolk$date_time)


data_temp_JuneOct2022_KanewaiFishpondShadeUnderXmasBerry <- data_temp_JuneOct2022_KanewaiFishpondShadeUnderXmasBerry %>%
  unite(date_time, date, time, sep = " ")

data_temp_JuneOct2022_KanewaiFishpondShadeUnderXmasBerry$date_time <- mdy_hms(data_temp_JuneOct2022_KanewaiFishpondShadeUnderXmasBerry$date_time)


data_temp_JuneOct2022_KanewaiSpringLedge <- data_temp_JuneOct2022_KanewaiSpringLedge %>%
  unite(date_time, date, time, sep = " ")

data_temp_JuneOct2022_KanewaiSpringLedge$date_time <- mdy_hms(data_temp_JuneOct2022_KanewaiSpringLedge$date_time)


data_temp_OctNov2022_KalauhaihaiGarage <- data_temp_OctNov2022_KalauhaihaiGarage %>%
  unite(date_time, date, time, sep = " ")

data_temp_OctNov2022_KalauhaihaiGarage$date_time <- mdy_hms(data_temp_OctNov2022_KalauhaihaiGarage$date_time)

data_temp_OctNov2022_KalauhaihaiMakaha <- data_temp_OctNov2022_KalauhaihaiMakaha %>%
  unite(date_time, date, time, sep = " ")

data_temp_OctNov2022_KalauhaihaiMakaha$date_time <- mdy_hms(data_temp_OctNov2022_KalauhaihaiMakaha$date_time)
```

#Rename Column Names
```{r column rename function temp}
mfhc_colname_temp <- function(a = NULL, b = NULL, c = NULL, x = "temp_celsius", y = "date_time" ){
  colnames(a)[which(names(a) == b)] <- x
  colnames(a)[which(names(a) == c)] <- y

  
  a <- a %>% 
    select(y, x)
  
  return(a)
}
```

```{r}
data_temp_Sept2021Feb2022_KalauhaihaiAuwaiUnderBridge <- mfhc_colname_temp(a = data_temp_Sept2021Feb2022_KalauhaihaiAuwaiUnderBridge, b = "temp_c_lgr_s_n_20970094_sen_s_n_20970094", c = "date_time_gmt_10_00")
```

```{r}
data_temp_Sept2021June2022_KalauhaihaiMakaha <- mfhc_colname_temp(a = data_temp_Sept2021June2022_KalauhaihaiMakaha, b = "temp_c_lgr_s_n_20970115_sen_s_n_20970115", c = "date_time_gmt_10_00")
```

```{r}
data_temp_MarApr2022_KalauhaihaiAuwai <- mfhc_colname_temp(a = data_temp_MarApr2022_KalauhaihaiAuwai, b = "temp_c_lgr_s_n_20970122_sen_s_n_20970122", c = "date_time_gmt_10_00")
```

```{r}
data_temp_MarApr2022_KalauhaihaiCoconutTree <- mfhc_colname_temp(a = data_temp_MarApr2022_KalauhaihaiCoconutTree, b = "temp_c_lgr_s_n_20970110_sen_s_n_20970110", c = "date_time_gmt_10_00")
```

```{r}
data_temp_MarApr2022_KalauhaihaiGarage <- mfhc_colname_temp(a = data_temp_MarApr2022_KalauhaihaiGarage, b = "temp_c_lgr_s_n_20970094_sen_s_n_20970094", c = "date_time_gmt_10_00")
```

```{r}
data_temp_MarApr2022_KalauhaihaiHighway <- mfhc_colname_temp(a = data_temp_MarApr2022_KalauhaihaiHighway, b = "temp_c_lgr_s_n_20970092_sen_s_n_20970092", c = "date_time_gmt_10_00")
```

```{r}
data_temp_MarApr2022_KalauhaihaiMakaha <- mfhc_colname_temp(a = data_temp_MarApr2022_KalauhaihaiMakaha, b = "temp_c_lgr_s_n_20970102_sen_s_n_20970102", c = "date_time_gmt_10_00")
```

```{r}
data_temp_MarApr2022_KalauhaihaiOctopusTree <- mfhc_colname_temp(a = data_temp_MarApr2022_KalauhaihaiOctopusTree, b = "temp_c_lgr_s_n_20970118_sen_s_n_20970118", c = "date_time_gmt_10_00")
```

```{r}
data_temp_JuneOct2022_KalauhaihaiGarage <- mfhc_colname_temp(a = data_temp_JuneOct2022_KalauhaihaiGarage, b = "temp_c_c_1", c = "date_time")
```

```{r}
data_temp_JuneOct2022_KalauhaihaiMakaha <- mfhc_colname_temp(a = data_temp_JuneOct2022_KalauhaihaiMakaha, b = "temp_c_c_1", c = "date_time")
```

```{r}
data_temp_JuneOct2022_KanewaiAuwaiMakaiSideFootBridge <- mfhc_colname_temp(a = data_temp_JuneOct2022_KanewaiAuwaiMakaiSideFootBridge, b = "temp_c_c_1", c = "date_time")
```

```{r}
data_temp_JuneOct2022_KanewaiFishpondShadeUnderXmasBerry <- mfhc_colname_temp(a = data_temp_JuneOct2022_KanewaiFishpondShadeUnderXmasBerry, b = "temp_c_c_1", c = "date_time")
```

```{r}
data_temp_JuneOct2022_KanewaiFishpondLedgeEdgeNorfolk <- mfhc_colname_temp(a = data_temp_JuneOct2022_KanewaiFishpondLedgeEdgeNorfolk, b = "temp_c_c_1", c = "date_time")
```

```{r}
data_temp_JuneOct2022_KanewaiSpringLedge <- mfhc_colname_temp(a = data_temp_JuneOct2022_KanewaiSpringLedge, b = "temp_c_c_1", c = "date_time")
```

```{r}
data_temp_OctNov2022_KalauhaihaiGarage <- mfhc_colname_temp(a = data_temp_OctNov2022_KalauhaihaiGarage, b = "temp_c_c_1", c = "date_time")
```

```{r}
data_temp_OctNov2022_KalauhaihaiMakaha <- mfhc_colname_temp(a = data_temp_OctNov2022_KalauhaihaiMakaha, b = "temp_c_c_1", c = "date_time")
```

```{r}
data_temp_Oct2022Feb2023_KanewaiAuwaiMakaiSideFootBridge <- mfhc_colname_temp(a = data_temp_Oct2022Feb2023_KanewaiAuwaiMakaiSideFootBridge, b = "temp_c_lgr_s_n_20970110_sen_s_n_20970110", c = "date_time_gmt_10_00")
```

```{r}
data_temp_Oct2022Feb2023_KanewaiFishpondLedgeEdgeNorfolk <- mfhc_colname_temp(a = data_temp_Oct2022Feb2023_KanewaiFishpondLedgeEdgeNorfolk, b = "temp_c_lgr_s_n_20970094_sen_s_n_20970094", c = "date_time_gmt_10_00")
```

```{r}
data_temp_Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry <- mfhc_colname_temp(a = data_temp_Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry, b = "temp_c_lgr_s_n_20970115_sen_s_n_20970115", c = "date_time_gmt_10_00")
```

```{r}
data_temp_Oct2022Feb2023_KanewaiSpringLedge <- mfhc_colname_temp(a = data_temp_Oct2022Feb2023_KanewaiSpringLedge, b = "temp_c_lgr_s_n_20970102_sen_s_n_20970102", c = "date_time_gmt_10_00")
```

```{r}
data_temp_Nov2022Feb2023_KalauhaihaiGarage <- mfhc_colname_temp(a = data_temp_Nov2022Feb2023_KalauhaihaiGarage, b = "temp_c_lgr_s_n_20970109_sen_s_n_20970109", c = "date_time_gmt_10_00")
```

```{r}
data_temp_Nov2022Feb2023_KalauhaihaiMakaha <- mfhc_colname_temp(a = data_temp_Nov2022Feb2023_KalauhaihaiMakaha, b = "temp_c_lgr_s_n_20970123_sen_s_n_20970123", c = "date_time_gmt_10_00")
```

```{r}
data_temp_FebApr2023_KalauhaihaiGarage <- mfhc_colname_temp(a = data_temp_FebApr2023_KalauhaihaiGarage, b = "temp_c_lgr_s_n_20970122_sen_s_n_20970122", c = "date_time_gmt_10_00")
```

```{r}
data_temp_FebApr2023_KalauhaihaiMakaha <- mfhc_colname_temp(a = data_temp_FebApr2023_KalauhaihaiMakaha, b = "temp_c_lgr_s_n_20970107_sen_s_n_20970107", c = "date_time_gmt_10_00")
```

```{r}
data_temp_FebApr2023_KanewaiAuwaiMakaiSideFootBridge <- mfhc_colname_temp(a = data_temp_FebApr2023_KanewaiAuwaiMakaiSideFootBridge, b = "temp_c_lgr_s_n_20970093_sen_s_n_20970093", c = "date_time_gmt_10_00")
```


```{r}
data_temp_FebApr2023_KanewaiFishpondLedgeEdgeNorfolk <- mfhc_colname_temp(a = data_temp_FebApr2023_KanewaiFishpondLedgeEdgeNorfolk, b = "temp_c_lgr_s_n_20970108_sen_s_n_20970108", c = "date_time_gmt_10_00")
```

```{r}
data_temp_FebApr2023_KanewaiFishpondShadeUnderXmasBerry <- mfhc_colname_temp(a = data_temp_FebApr2023_KanewaiFishpondShadeUnderXmasBerry, b = "temp_c_lgr_s_n_21445019_sen_s_n_21445019", c = "date_time_gmt_10_00")
```

```{r}
data_temp_FebApr2023_KanewaiSpringLedge <- mfhc_colname_temp(a = data_temp_FebApr2023_KanewaiSpringLedge, b = "temp_c_lgr_s_n_20970092_sen_s_n_20970092", c = "date_time_gmt_10_00")
```

#Remove the hour indicator
```{r}
data_temp_MarApr2022_KalauhaihaiAuwai$date_time <- gsub("\\AM|\\PM", "", data_temp_MarApr2022_KalauhaihaiAuwai$date_time)

data_temp_MarApr2022_KalauhaihaiCoconutTree$date_time <- gsub("\\AM|\\PM", "", data_temp_MarApr2022_KalauhaihaiCoconutTree$date_time)

data_temp_MarApr2022_KalauhaihaiGarage$date_time <- gsub("\\AM|\\PM", "", data_temp_MarApr2022_KalauhaihaiGarage$date_time)

data_temp_MarApr2022_KalauhaihaiHighway$date_time <- gsub("\\AM|\\PM", "", data_temp_MarApr2022_KalauhaihaiHighway$date_time)

data_temp_MarApr2022_KalauhaihaiMakaha$date_time <- gsub("\\AM|\\PM", "", data_temp_MarApr2022_KalauhaihaiMakaha$date_time)

data_temp_MarApr2022_KalauhaihaiOctopusTree$date_time <- gsub("\\AM|\\PM", "", data_temp_MarApr2022_KalauhaihaiOctopusTree$date_time)

data_temp_Nov2022Feb2023_KalauhaihaiGarage$date_time <- gsub("\\AM|\\PM", "", data_temp_Nov2022Feb2023_KalauhaihaiGarage$date_time)

data_temp_Nov2022Feb2023_KalauhaihaiMakaha$date_time <- gsub("\\AM|\\PM", "", data_temp_Nov2022Feb2023_KalauhaihaiMakaha$date_time)

data_temp_Oct2022Feb2023_KanewaiAuwaiMakaiSideFootBridge$date_time <- gsub("\\AM|\\PM", "", data_temp_Oct2022Feb2023_KanewaiAuwaiMakaiSideFootBridge$date_time)

data_temp_Oct2022Feb2023_KanewaiFishpondLedgeEdgeNorfolk$date_time <- gsub("\\AM|\\PM", "", data_temp_Oct2022Feb2023_KanewaiFishpondLedgeEdgeNorfolk$date_time)

data_temp_Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry$date_time <- gsub("\\AM|\\PM", "", data_temp_Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry$date_time)

data_temp_Oct2022Feb2023_KanewaiSpringLedge$date_time <- gsub("\\AM|\\PM", "", data_temp_Oct2022Feb2023_KanewaiSpringLedge$date_time)

```


# Convert  date/time column to UTC class in .csv data

```{r}
data_temp_Sept2021Feb2022_KalauhaihaiAuwaiUnderBridge$date_time <- mdy_hms(data_temp_Sept2021Feb2022_KalauhaihaiAuwaiUnderBridge$date_time)

data_temp_Sept2021June2022_KalauhaihaiMakaha$date_time <- mdy_hms(data_temp_Sept2021June2022_KalauhaihaiMakaha$date_time)

data_temp_MarApr2022_KalauhaihaiAuwai$date_time <- mdy_hms(data_temp_MarApr2022_KalauhaihaiAuwai$date_time)

data_temp_MarApr2022_KalauhaihaiCoconutTree$date_time <- mdy_hms(data_temp_MarApr2022_KalauhaihaiCoconutTree$date_time)

data_temp_MarApr2022_KalauhaihaiGarage$date_time <- mdy_hms(data_temp_MarApr2022_KalauhaihaiGarage$date_time)

data_temp_MarApr2022_KalauhaihaiHighway$date_time <- mdy_hms(data_temp_MarApr2022_KalauhaihaiHighway$date_time)

data_temp_MarApr2022_KalauhaihaiMakaha$date_time <- mdy_hms(data_temp_MarApr2022_KalauhaihaiMakaha$date_time)

data_temp_MarApr2022_KalauhaihaiOctopusTree$date_time <- mdy_hms(data_temp_MarApr2022_KalauhaihaiOctopusTree$date_time)

data_temp_Nov2022Feb2023_KalauhaihaiGarage$date_time <- mdy_hms(data_temp_Nov2022Feb2023_KalauhaihaiGarage$date_time)

data_temp_Nov2022Feb2023_KalauhaihaiMakaha$date_time <- mdy_hms(data_temp_Nov2022Feb2023_KalauhaihaiMakaha$date_time)

data_temp_Oct2022Feb2023_KanewaiAuwaiMakaiSideFootBridge$date_time <- mdy_hms(data_temp_Oct2022Feb2023_KanewaiAuwaiMakaiSideFootBridge$date_time)

data_temp_Oct2022Feb2023_KanewaiFishpondLedgeEdgeNorfolk$date_time <- mdy_hms(data_temp_Oct2022Feb2023_KanewaiFishpondLedgeEdgeNorfolk$date_time)

data_temp_Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry$date_time <- mdy_hms(data_temp_Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry$date_time)

data_temp_Oct2022Feb2023_KanewaiSpringLedge$date_time <- mdy_hms(data_temp_Oct2022Feb2023_KanewaiSpringLedge$date_time)

data_temp_FebApr2023_KalauhaihaiGarage$date_time <- mdy_hms(data_temp_FebApr2023_KalauhaihaiGarage$date_time)

data_temp_FebApr2023_KalauhaihaiMakaha$date_time <- mdy_hms(data_temp_FebApr2023_KalauhaihaiMakaha$date_time)

data_temp_FebApr2023_KanewaiAuwaiMakaiSideFootBridge$date_time <- mdy_hms(data_temp_FebApr2023_KanewaiAuwaiMakaiSideFootBridge$date_time)

data_temp_FebApr2023_KanewaiFishpondLedgeEdgeNorfolk$date_time <- mdy_hms(data_temp_FebApr2023_KanewaiFishpondLedgeEdgeNorfolk$date_time)

data_temp_FebApr2023_KanewaiFishpondShadeUnderXmasBerry$date_time <- mdy_hms(data_temp_FebApr2023_KanewaiFishpondShadeUnderXmasBerry$date_time)

data_temp_FebApr2023_KanewaiSpringLedge$date_time <- mdy_hms(data_temp_FebApr2023_KanewaiSpringLedge$date_time)
```

# Format data to be joined with other variables and locations

# Add location columns

```{r}
data_temp_Sept2021Feb2022_KalauhaihaiAuwaiUnderBridge <- 
data_temp_Sept2021Feb2022_KalauhaihaiAuwaiUnderBridge %>% 
  mutate(site = "Kalauhaihai")

data_temp_Sept2021June2022_KalauhaihaiMakaha <- data_temp_Sept2021June2022_KalauhaihaiMakaha %>% 
  mutate(site = "Kalauhaihai")

data_temp_MarApr2022_KalauhaihaiAuwai <- 
data_temp_MarApr2022_KalauhaihaiAuwai %>% 
  mutate(site = "Kalauhaihai")

data_temp_MarApr2022_KalauhaihaiCoconutTree <- 
data_temp_MarApr2022_KalauhaihaiCoconutTree %>% 
  mutate(site = "Kalauhaihai")

data_temp_MarApr2022_KalauhaihaiGarage <- 
data_temp_MarApr2022_KalauhaihaiGarage %>% 
  mutate(site = "Kalauhaihai")

data_temp_MarApr2022_KalauhaihaiHighway <- 
data_temp_MarApr2022_KalauhaihaiHighway %>% 
  mutate(site = "Kalauhaihai")

data_temp_MarApr2022_KalauhaihaiMakaha <- 
data_temp_MarApr2022_KalauhaihaiMakaha %>% 
  mutate(site = "Kalauhaihai")

data_temp_MarApr2022_KalauhaihaiOctopusTree <- 
data_temp_MarApr2022_KalauhaihaiOctopusTree %>% 
  mutate(site = "Kalauhaihai")

data_temp_JuneOct2022_KalauhaihaiGarage <- 
data_temp_JuneOct2022_KalauhaihaiGarage %>% 
  mutate(site = "Kalauhaihai")

data_temp_JuneOct2022_KalauhaihaiMakaha <- 
data_temp_JuneOct2022_KalauhaihaiMakaha %>% 
  mutate(site = "Kalauhaihai")

data_temp_JuneOct2022_KanewaiAuwaiMakaiSideFootBridge <- 
data_temp_JuneOct2022_KanewaiAuwaiMakaiSideFootBridge %>% 
  mutate(site = "Kanewai")

data_temp_JuneOct2022_KanewaiFishpondShadeUnderXmasBerry <- 
data_temp_JuneOct2022_KanewaiFishpondShadeUnderXmasBerry %>% 
  mutate(site = "Kanewai")

data_temp_JuneOct2022_KanewaiFishpondLedgeEdgeNorfolk <- 
data_temp_JuneOct2022_KanewaiFishpondLedgeEdgeNorfolk %>% 
  mutate(site = "Kanewai")

data_temp_JuneOct2022_KanewaiSpringLedge <- 
data_temp_JuneOct2022_KanewaiSpringLedge %>% 
  mutate(site = "Kanewai")

data_temp_JuneOct2022_KanewaiSpringLedge <- 
data_temp_JuneOct2022_KanewaiSpringLedge %>% 
  mutate(site = "Kanewai")

data_temp_OctNov2022_KalauhaihaiGarage <- 
data_temp_OctNov2022_KalauhaihaiGarage %>% 
  mutate(site = "Kalauhaihai")

data_temp_OctNov2022_KalauhaihaiMakaha <- 
data_temp_OctNov2022_KalauhaihaiMakaha %>% 
  mutate(site = "Kalauhaihai")

data_temp_Oct2022Feb2023_KanewaiAuwaiMakaiSideFootBridge <- 
data_temp_Oct2022Feb2023_KanewaiAuwaiMakaiSideFootBridge %>% 
  mutate(site = "Kanewai")

data_temp_Oct2022Feb2023_KanewaiFishpondLedgeEdgeNorfolk <- 
data_temp_Oct2022Feb2023_KanewaiFishpondLedgeEdgeNorfolk %>% 
  mutate(site = "Kanewai")

data_temp_Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry <- 
data_temp_Oct2022Feb2023_KanewaiFishpondShadeUnderXmasBerry %>% 
  mutate(site = "Kanewai")

data_temp_Oct2022Feb2023_KanewaiSpringLedge <- 
data_temp_Oct2022Feb2023_KanewaiSpringLedge %>% 
  mutate(site = "Kanewai")

data_temp_Nov2022Feb2023_KalauhaihaiGarage <- 
data_temp_Nov2022Feb2023_KalauhaihaiGarage %>% 
  mutate(site = "Kalauhaihai")

data_temp_Nov2022Feb2023_KalauhaihaiMakaha <- 
data_temp_Nov2022Feb2023_KalauhaihaiMakaha %>% 
  mutate(site = "Kalauhaihai")

data_temp_FebApr2023_KalauhaihaiGarage <- 
data_temp_FebApr2023_KalauhaihaiGarage %>% 
  mutate(site = "Kalauhaihai")

data_temp_FebApr2023_KalauhaihaiMakaha <- 
data_temp_FebApr2023_KalauhaihaiMakaha %>% 
  mutate(site = "Kalauhaihai")

data_temp_FebApr2023_KanewaiAuwaiMakaiSideFootBridge <- 
data_temp_FebApr2023_KanewaiAuwaiMakaiSideFootBridge %>% 
  mutate(site = "Kanewai")

data_temp_FebApr2023_KanewaiFishpondLedgeEdgeNorfolk <- 
data_temp_FebApr2023_KanewaiFishpondLedgeEdgeNorfolk %>% 
  mutate(site = "Kanewai")

data_temp_FebApr2023_KanewaiFishpondShadeUnderXmasBerry <- 
data_temp_FebApr2023_KanewaiFishpondShadeUnderXmasBerry %>% 
  mutate(site = "Kanewai")

data_temp_FebApr2023_KanewaiSpringLedge <- 
data_temp_FebApr2023_KanewaiSpringLedge %>% 
  mutate(site = "Kanewai")

```



# Maybe Trimming
