---
title: "Joining oxygen, pH, conductivity & temperature"
author: "Connor Flynn"
date: "7/18/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(naniar)
```


Read in Cleaned Data

```{r}
cleaned_conductivity <- read_csv(here("cleaned_data/cleaned_conductivity/conductivity_joined.csv"))

cleaned_oxygen <- read_csv(here("cleaned_data/cleaned_oxygen/oxygen_joined.csv"))

cleaned_pH <- read_csv(here("cleaned_data/cleaned_pH/pH_joined.csv"))

cleaned_temperature <- read_csv(here("cleaned_data/cleaned_temperature/temp_joined.csv"))

```


Join Data using bind_rows()

```{r}
all_data <- bind_rows(cleaned_conductivity, cleaned_oxygen, cleaned_pH, cleaned_temperature)
```

Check Na's

```{r}
miss_var_summary(all_data)
```
```{r}
duplicates <- all_data %>%
    dplyr::group_by(date_time, site, site_specific, variable, value) %>%
    dplyr::summarise(n = dplyr::n(), .groups = "drop") %>%
    dplyr::filter(n > 1)
```


Write Master-Dataframe

```{r}
write_csv(all_data, here("cleaned_data/master_dataframe.csv"))
```

